services:
  clothing-store-backend:
    container_name: clothing-store-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BREVO_API_KEY: ${BREVO_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY:-mock}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY:-mock}
      AWS_REGION: ${AWS_REGION:-ap-southeast-1}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    networks:
      - default

networks:
  default:
    name: clothing-store-service